# Generated by Django 5.2.4 on 2025-08-04 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmrspce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('unlisted', 'Unlisted (viewable with link)')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('collection', 'Same as Collection')], default='collection', max_length=10),
        ),
        migrations.CreateModel(
            name='CollectionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit Items'), ('manage', 'Manage Collection')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='hmmrspce.collection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_shares_created', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('collection', 'shared_with')},
            },
        ),
    ]
